dialogue(:bottom, "Oh dear, looks like I'm stranded here on this island.", player)
dialogue(:top, "Yep, it certainly seems that way.", player)
dialogue(:bottom, "I'm talking to myself now.", player)
dialogue(:top, "Yes.", player)
dialogue(:middle, "OBJECTIVE: Find a way off the island!")